name: "Test Action"

on:
  push:
    branches:
      - "**"

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all
      - id: default
        uses: ./
      - name: Test current commit hash is used by default
        uses: pr-mpt/actions-assert@v1
        with:
          assertion: npm://@assertions/is-equal
          expected: "${{ github.sha }}"
          actual: ${{ steps.default.outputs.long }}
      - id: example
        uses: ./
        with:
          commit: 734713bc047d87bf7eac9674765ae793478c50d3
      - name: Test commit hash is used when provided
        uses: pr-mpt/actions-assert@v1
        with:
          assertion: npm://@assertions/is-equal
          expected: "734713bc047d87bf7eac9674765ae793478c50d3"
          actual: ${{ steps.example.outputs.long }}
      - name: Test short commit hash is extracted from long
        uses: pr-mpt/actions-assert@v1
        with:
          assertion: npm://@assertions/is-equal
          expected: "734713b"
          actual: ${{ steps.example.outputs.short }}
